### ISSUE TITLE
[Preprocessing Issue] jjson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by BupyeongHealer** [IIT-PAVIS/SpatialCommonsenseGraph#1]
HI, Thanks to sharing great work!

I have some issue for preprocessing scannet.
Did you know the solution to this problem?

Sincerely,

==========================================================
(spatialgraph) hello96min@rvi-node001:~/minseok/SpatialCommonsenseGraph/DATASET_GENERATION$ python 1.create_annotated_ply.py 
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1513/1513 [00:00<00:00, 5738.85it/s]

Creating the annotated PCD for the full scenes in the folder 'annotated_ply', please wait, this may take a while

  9%|████████▌                                                                                            | 129/1513 [00:42<07:32,  3.06it/s]
Traceback (most recent call last):
  File "1.create_annotated_ply.py", line 119, in <module>
    main()
  File "1.create_annotated_ply.py", line 112, in main
    result = ray.get(finished)
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/site-packages/ray/worker.py", line 1763, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(JSONDecodeError): ray::parse_scene() (pid=56307, ip=10.20.22.128)
  File "1.create_annotated_ply.py", line 28, in parse_scene
    json_aggregation = json.load(json_data)
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(spatialgraph) hello96min@rvi-node001:~/minseok/SpatialCommonsenseGraph/DATASET_GENERATION$ python 1.create_annotated_ply.py 
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1513/1513 [00:00<00:00, 5750.16it/s]

Creating the annotated PCD for the full scenes in the folder 'annotated_ply', please wait, this may take a while

 35%|███████████████████████████████████▊                                                                 | 537/1513 [02:41<04:53,  3.33it/s]
Traceback (most recent call last):
  File "1.create_annotated_ply.py", line 119, in <module>
    main()
  File "1.create_annotated_ply.py", line 112, in main
    result = ray.get(finished)
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/site-packages/ray/worker.py", line 1763, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(JSONDecodeError): ray::parse_scene() (pid=62163, ip=10.20.22.128)
  File "1.create_annotated_ply.py", line 28, in parse_scene
    json_aggregation = json.load(json_data)
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hello96min/yes/envs/spatialgraph/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by BupyeongHealer** [comment]
I solve it.
The problem is scannet/scene201_01/scene0201_01_vh_clean.aggregation.json.
It is an empty file. I remove this folder.

Thanks anyway!
